const data = [
  {
    ten: "Ám Ảnh Từ Kiếp Trước - Bí Mật Của Sự Sống Và Cái Chết (Tái Bản 2020)",
    tacGia: "Brian L. Weiss",
    nhaXuatBan: "Nhà Xuất Bản Lao Động",
    giaSach: "63.600",
    moTa: "Cuốn sách hay và khiêu khích suy nghĩ này đã phá vở những rào cản trong trị liệu tâm lý truyền thống và trình bày một biện pháp trị liệu cách tân và hiệu quả cao. Những ai làm việc chuyên về sức khỏe tâm thần cần phải xem xét nó nghiêm túc.” – Edith Fiore, TS., bác sỹ tâm lý học lâm sàng và là tác giả cuốn sách Bạn từng ở đây trước kia (You Have Been Here Before",
    hinhAnh:
      "https://lh3.googleusercontent.com/u/0/drive-viewer/AAOQEOS3AarFNKWlpe592TDxobm9lCYNSlx-XeFKnu4mu_N46-2MdJ7Ukb3I9h-FfXvGkvzQ6c5tRG-v18dl1WGZ70eLtrgIaw=w1920-h892",
    ngayThem: "15/10/2020",
    ngayXuatBan: "15/10/2020",
    ngayCapNhat: "15/10/2020",
    soLuong: "200",
    khuyenMai: "CÁi quần què nè",
    danhMuc: {
      idDanhMuc: 1,
      ten: "Tâm linh",
      moTa: "asasassasaasa",
    },
  },
  {
    ten: "Hành Tinh Của Một Kẻ Nghĩ Nhiều",
    tacGia: "Amateur Psychology Nguyễn Đoàn Minh Thư",
    nhaXuatBan: "Thế Giới",
    giaSach: "64.500",
    moTa: "Hành Tinh Của Một Kẻ Nghĩ Nhiều “Đó là mùa hè năm 2020, mùa hè của COVID-19 và một ngàn vạn khủng hoảng tuổi đôi mươi. Đó là mùa hè mình bắt chuyến bay sớm nhất có thể vào ngày 20 tháng 3 để chạy khỏi nước Anh đang bùng dịch, bị kẹt lại sân bay Bangkok trong 24 giờ đồng hồ vì chuyến bay quá cảnh về Sài Gòn bị huỷ",
    hinhAnh:
      "  https://lh3.googleusercontent.com/u/0/drive-viewer/AAOQEOQQA0IECIlRZa4yxb8EYkGIcMbmPuIPFc1clpxAqunAj4RIh06IkDVzlVp_81ccjO-RF89QMBbEzITJW9apd5aeh_xBGQ=w1920-h892",
    ngayThem: "01/01/2023",
    ngayXuatBan: "01/01/2023",
    ngayCapNhat: "01/01/2023",
    soLuong: "10",
    khuyenMai: "cái quần què",
    danhMuc: {
      idDanhMuc: 2,
      ten: "Tâm lý",
      moTa: "asasassasaasa",
    },
  },
  {
    ten: "Hiểu Về Trái Tim (Tái Bản 2023)",
    tacGia: "Minh Niệm",
    nhaXuatBan: "Tổng Hợp TPHCM",
    giaSach: "134.300",
    moTa: "“Hiểu về trái tim” là một cuốn sách đặc biệt được viết bởi thiền sư Minh Niệm. Với phong thái và lối hành văn gần gũi với những sinh hoạt của người Việt, thầy Minh Niệm đã thật sự thổi hồn Việt vào cuốn sách nhỏ này",
    hinhAnh:
      "https://lh3.googleusercontent.com/u/0/drive-viewer/AAOQEOTLuPwv2NxsGuzXQbLAaXi-ofDp7MHamzyyMEzQAJUPs5Aj6DuWZl8X77PWA5N3-UFo0sgKcC155JdqPjSysUazSjF4hQ=w1920-h892",
    ngayThem: "01/01/2023",
    ngayXuatBan: "01/01/2023",
    ngayCapNhat: "01/01/2023",
    soLuong: "350",
    khuyenMai: "cái quần què",
    danhMuc: {
      idDanhMuc: 2,
      ten: "Tâm lý",
      moTa: "trái tim” là một cuốn sách đặc biệt",
    },
  },
  {
    ten: "Kiếp Nào Ta Cũng Tìm Thấy Nhau: Câu Chuyện Về Những Linh Hồn Tri Kỷ Vĩnh Viễn Không Chia Lìa (Tái Bản)",
    tacGia: "Brian L Weiss",
    nhaXuatBan: "Nhà Xuất Bản Lao Động",
    giaSach: "65.800",
    moTa: "Kiếp nào ta cũng tìm thấy nhau là cuốn sách thứ ba của Brain L. Weiss – một nhà tâm thần học có tiếng. Trước đó ông đã viết hai cuốn sách: cuốn đầu tiên là Ám ảnh từ kiếp trước, cuốn sách mô tả câu chuyện có thật về một bệnh nhân trẻ tuổi cùng với những liệu pháp thôi miên về kiếp trước đã làm thay đổi cả cuộc đời tác giả lẫn cô ấy. Cuốn sách đã bán chạy trên toàn thế giới với hơn 2 triệu bản in và được dịch sang hơn 20 ngôn ngữ. Cuốn sách thứ hai Through Time into Healing (Đi qua thời gian để chữa lành), mô tả những gì tác giả đã học được về tiềm năng chữa bệnh của liệu pháp hồi quy tiền kiếp. Trong cuốn sách đều là những câu chuyện người thật việc thật. Nhưng câu chuyện hấp dẫn nhất lại nằm trong cuốn sách thứ ba.GOETHE",
    hinhAnh:
      "https://lh3.googleusercontent.com/u/0/drive-viewer/AAOQEOTKsEQ3vkK1XDyrli4UVzBjaW4PsouwFm4ulv-2YHsFPklfgGFwCQwM82b5r3kC26RHCb1g2EMpLZk-DXvd6m54lO3zkA=w1920-h892",
    ngayThem: "02/02/2022",
    ngayXuatBan: "02/02/2022",
    ngayCapNhat: "02/02/2022",
    soLuong: "950",
    khuyenMai: "950",
    danhMuc: {
      idDanhMuc: 3,
      ten: "Tâm linh",
      moTa: "trái tim” là một cuốn sách đặc biệt",
    },
  },
  {
    ten: "Nhân Duyên Tiền Kiếp",
    tacGia: "Dick Sutphen",
    nhaXuatBan: "Nhà Xuất Bản Thanh Niên",
    giaSach: "155.000",
    moTa: "“Tuyệt đối không nghi ngờ gì nữa, các cặp đôi đang bên nhau ở kiếp này đã từng ở bên nhau trong nhiều kiếp trước…",
    hinhAnh:
      "https://lh3.googleusercontent.com/u/0/drive-viewer/AAOQEORWp8iprcAq1OtNvwx6WneNTvjHoZw8-3PxtKD_Hy4Cnru3Ru09V1X74hI9b0Ef9zw2MWYSSxdba_5z3Uhd6skKKVyyOA=w1920-h892",
    ngayThem: "11/11/2022",
    ngayXuatBan: "11/11/2022",
    ngayCapNhat: "11/11/2022",
    soLuong: "300",
    khuyenMai: "cái quần què",
    danhMuc: {
      idDanhMuc: 1,
      ten: "Tâm linh",
      moTa: "trái tim” là một cuốn sách đặc biệt",
    },
  },
  {
    ten: "A ! Tết Là Đây !",
    tacGia: "Vũ Linh  Komorebi  Quyên Thái",
    nhaXuatBan: "NXB Kim Đồng",
    giaSach: "68.000",
    moTa: "Một cuốn sách Tết “động đậy” nhất từ trước đến nay dành cho các bé! Tương tác - Tưởng tượng – Thích thú cùng những trang sách đầy bất ngờ, cho bé trải nghiệm những hoạt động và trò chơi nhằm phát triển khả năng sắp xếp, phân loại, tư duy logic và sáng tạo. “Sột soạt…sột…soạt…” Ồ, bé nghe thấy gì không? Cuốn sách đang mời gọi đấy!",
    hinhAnh:
      "https://lh3.googleusercontent.com/u/0/drive-viewer/AAOQEOSfPoB9IQQ1eMvGifHxBTGN3GMQii5mOF2StTuQ3rM7870pO2hRdI5KazKLXt_cZA_PbzISq5Ibl4kgBX20Y3jwoYyq=w1062-h840",
    ngayThem: "17/12/2022",
    ngayXuatBan: "17/12/2022",
    ngayCapNhat: "17/12/2022",
    soLuong: "300",
    khuyenMai: "Cái quần què",
    danhMuc: {
      idDanhMuc: 2,
      ten: "Tâm linh",
      moTa: "trái tim” là một cuốn sách đặc biệt",
    },
  },
  {
    ten: "Bài Học Đầu Đời Cho Bé - Không Được Đụng Vào Đồ Của Tớ",
    tacGia: "Chú Tiểu Dương",
    nhaXuatBan: "NXB Hà Nội",
    giaSach: "38.000",
    moTa: "Giúp Trẻ Biết Chia Sẻ, Nhường Nhịn Và Không Ích Kỷ",
    hinhAnh:
      "https://lh3.googleusercontent.com/u/0/drive-viewer/AAOQEOQBEvktmfdGV0Ur11I6zXjXpo37rvfkfREPZyKcZB60Ntru36jCHTPtNNbZzJh1ylaaLDmp2QvnagByIMZ57bjZsEX18Q=w1920-h892",
    ngayThem: "17/12/2022",
    ngayXuatBan: "17/12/2022",
    ngayCapNhat: "17/12/2022",
    soLuong: "300",
    khuyenMai: "Cái quần què",
    danhMuc: {
      idDanhMuc: 2,
      ten: "Tâm linh",
      moTa: "trái tim” là một cuốn sách đặc biệt",
    },
  },
  {
    ten: "Bánh Mì Kẹp Chuột (Tái Bản 2019)",
    tacGia: "David Walliams",
    nhaXuatBan: "Nhã Nam",
    giaSach: "64.100",
    moTa: "Zoe luôn mơ ước được có một sô diễn xiếc chuột của riêng mình, nhưng chú chuột hamster của con bé đã chết một cách đột ngột, còn chuột cưng mới thì đang gặp nguy hiểm chết người.- The Sun",
    hinhAnh:
      "https://lh3.googleusercontent.com/u/0/drive-viewer/AAOQEOTbx6zMHY2r7yNbOeJvqKynjcsKtOHJ3gBa1-4ki74blWh2FFGLI6-uZGkZlWanoKIW-HstGYAnq1JHo3jSAHXurd1I_w=w1920-h892",
    ngayThem: "04/10/2019",
    ngayXuatBan: "04/10/2019",
    ngayCapNhat: "04/10/2019",
    soLuong: "80",
    khuyenMai: "cái quần què",
    danhMuc: {
      idDanhMuc: 3,
      ten: "Tâm linh",
      moTa: "trái tim” là một cuốn sách đặc biệt",
    },
  },
  {
    ten: "Bịt Mắt Bắt Mèo",
    tacGia: "Lê Thư",
    nhaXuatBan: "NXB Trẻ",
    giaSach: "42.500",
    moTa: "Truyện dài kỳ về Mèo. Các bạn mèo nhà mình sẽ hướng dẫn các bé chơi các trò chơi dân gian theo cách thật sinh động, hài hước, dễ thương.",
    hinhAnh:
      "https://lh3.googleusercontent.com/u/0/drive-viewer/AAOQEOR_hJFeVlxdihYMu_Ketyvb-SId0DaHuEhy1vxiJvawuL24hkAlJmuu9vwTwZB6Wp_T63dTksqLFQmG2h3grat4v5lz0g=w1920-h892",
    ngayThem: "15/03/2023",
    ngayXuatBan: "15/03/2023",
    ngayCapNhat: "15/03/2023",
    soLuong: "5",
    khuyenMai: "cái quần què",
    danhMuc: {
      idDanhMuc: 2,
      ten: "Tâm linh",
      moTa: "trái tim” là một cuốn sách đặc biệt",
    },
  },
  {
    ten: "Câu Hỏi Trẻ Thơ",
    tacGia: "Lê Phương Liên",
    nhaXuatBan: "NXB Kim Đồng",
    giaSach: "74.500",
    moTa: "“Cuốn sách các bạn cầm trên tay đây đã được viết trong 50 năm (1970- 2020). Một tuyển tập bao gồm 25 truyện ngắn và 25 tản văn được chọn từ các truyện ngắn và tản văn đã được giải thưởng trong các cuộc thi văn học, đã được in trên báo, in trong các cuốn sách của riêng tác giả hoặc các tuyển tập chung. Cuốn sách này dành cho mọi lứa tuổi từ các học sinh tiểu học đến các cụ các bác đã nghỉ hưu. Những dòng văn trong cuốn sách là lời tâm tình của một nhà giáo, một nhà văn, một cán bộ biên tập của Nhà xuất bản Kim Đồng và cũng là một người mẹ. Bạn đọc sẽ được theo tác giả đi tới nhiều vùng miền của đất nước Việt Nam và cũng ghé thăm một vài nơi trên thế giới mà tác giả đã có dịp đặt chân đến. Những trang sách mộc mạc này gửi gắm tình cảm yêu thương đến gia đình, quê hương, tới những bạn lớn những người bạn quý đã để lại ấn tượng sâu sắc trong kí ức của tác giả. Hi vọng rằng những trang sách sẽ đem lại cho người đọc những phút giây đầm ấm yêu thương, gửi đến các bạn những suy nghĩ tươi sáng về cuộc sống và con người.” (Nhà văn LÊ PHƯƠNG LIÊN)                                                                                                                                                 “Từ thuở ấu thơ cho đến lúc trưởng thành lẽ sống của tôi là tình yêu thương con người nhất là những người bé bỏng như trẻ em. Tâm tình ấy là do mẹ tôi và bà tôi đã ươm mầm từ khi còn nhỏ. Tôi sớm có một niềm khát khao vươn lên để hiểu biết tinh hoa trí tuệ loài người và mong mỏi được sống trong xã hội thắm tình yêu thương chân thật. Niềm khát khao ấy đã thôi thúc tôi cầm bút viết văn từ tuổi thanh xuân, trải qua những vất vả thăng trầm nỗi niềm ấy vẫn khiến tôi viết tiếp và viết mãi… Phần lớn những dòng chữ trong cuốn sách này tôi đã viết khi mẹ tôi không còn nữa. Mỗi khi viết được những dòng ngay ngắn tôi lại thấy trên cao xanh xa xa, mẹ tôi đang nhìn tôi và mỉm cười trìu mến vô cùng.” (LÊ PHƯƠNG LIÊN)                                                           “Viết cho thiếu nhi rất khó. Viết cho lứa tuổi nhi đồng mẫu giáo còn khó hơn nhiều. Lê Phương Liên đã chọn con đường khó nhất ấy để tạo dựng sự nghiệp cho mình. Với tâm hồn trong trẻo, tinh tế và nhạy cảm, lại thêm lối kể chuyện mộc mạc, giản dị mà không kém phần hấp dẫn, sâu sắc… văn của chị là những món quà đặc biệt đã “thửa” riêng dâng tặng con trẻ và những ai từng là con trẻ.” (Nhà thơ TRẦN ĐĂNG KHOA)",
    hinhAnh:
      "https://lh3.googleusercontent.com/u/0/drive-viewer/AAOQEOSw-OumEa2WSYcHOZH6kpt5Y8qvZYtKJSZimV3R-vZLavAFz3SKmvHLIk7188KpdQtMmhBgQO_pUNqXag7sZtmeiTNsDA=w1920-h892",
    ngayThem: "19/11/2020",
    ngayXuatBan: "19/11/2020",
    ngayCapNhat: "19/11/2020",
    soLuong: "100",
    khuyenMai: "cái quần què",
    danhMuc: {
      idDanhMuc: 2,
      ten: "Tâm linh",
      moTa: "trái tim” là một cuốn sách đặc biệt",
    },
  },
  {
    ten: "Ám Ảnh Từ Kiếp Trước - Bí Mật Của Sự Sống Và Cái Chết (Tái Bản 2020)",
    tacGia: "Brian L. Weiss",
    nhaXuatBan: "Nhà Xuất Bản Lao Động",
    giaSach: "63.600",
    moTa: "Cuốn sách hay và khiêu khích suy nghĩ này đã phá vở những rào cản trong trị liệu tâm lý truyền thống và trình bày một biện pháp trị liệu cách tân và hiệu quả cao. Những ai làm việc chuyên về sức khỏe tâm thần cần phải xem xét nó nghiêm túc.” – Edith Fiore, TS., bác sỹ tâm lý học lâm sàng và là tác giả cuốn sách Bạn từng ở đây trước kia (You Have Been Here Before",
    hinhAnh:
      "https://lh3.googleusercontent.com/u/0/drive-viewer/AAOQEOS3AarFNKWlpe592TDxobm9lCYNSlx-XeFKnu4mu_N46-2MdJ7Ukb3I9h-FfXvGkvzQ6c5tRG-v18dl1WGZ70eLtrgIaw=w1920-h892",
    ngayThem: "15/10/2020",
    ngayXuatBan: "15/10/2020",
    ngayCapNhat: "15/10/2020",
    soLuong: "200",
    khuyenMai: "CÁi quần què nè",
    danhMuc: {
      idDanhMuc: 1,
      ten: "Tâm linh",
      moTa: "asasassasaasa",
    },
  },
  {
    ten: "Hành Tinh Của Một Kẻ Nghĩ Nhiều",
    tacGia: "Amateur Psychology Nguyễn Đoàn Minh Thư",
    nhaXuatBan: "Thế Giới",
    giaSach: "64.500",
    moTa: "Hành Tinh Của Một Kẻ Nghĩ Nhiều “Đó là mùa hè năm 2020, mùa hè của COVID-19 và một ngàn vạn khủng hoảng tuổi đôi mươi. Đó là mùa hè mình bắt chuyến bay sớm nhất có thể vào ngày 20 tháng 3 để chạy khỏi nước Anh đang bùng dịch, bị kẹt lại sân bay Bangkok trong 24 giờ đồng hồ vì chuyến bay quá cảnh về Sài Gòn bị huỷ",
    hinhAnh:
      "  https://lh3.googleusercontent.com/u/0/drive-viewer/AAOQEOQQA0IECIlRZa4yxb8EYkGIcMbmPuIPFc1clpxAqunAj4RIh06IkDVzlVp_81ccjO-RF89QMBbEzITJW9apd5aeh_xBGQ=w1920-h892",
    ngayThem: "01/01/2023",
    ngayXuatBan: "01/01/2023",
    ngayCapNhat: "01/01/2023",
    soLuong: "10",
    khuyenMai: "cái quần què",
    danhMuc: {
      idDanhMuc: 1,
      ten: "Tâm lý",
      moTa: "asasassasaasa",
    },
  },
  {
    ten: "Hiểu Về Trái Tim (Tái Bản 2023)",
    tacGia: "Minh Niệm",
    nhaXuatBan: "Tổng Hợp TPHCM",
    giaSach: "134.300",
    moTa: "“Hiểu về trái tim” là một cuốn sách đặc biệt được viết bởi thiền sư Minh Niệm. Với phong thái và lối hành văn gần gũi với những sinh hoạt của người Việt, thầy Minh Niệm đã thật sự thổi hồn Việt vào cuốn sách nhỏ này",
    hinhAnh:
      "https://lh3.googleusercontent.com/u/0/drive-viewer/AAOQEOTLuPwv2NxsGuzXQbLAaXi-ofDp7MHamzyyMEzQAJUPs5Aj6DuWZl8X77PWA5N3-UFo0sgKcC155JdqPjSysUazSjF4hQ=w1920-h892",
    ngayThem: "01/01/2023",
    ngayXuatBan: "01/01/2023",
    ngayCapNhat: "01/01/2023",
    soLuong: "350",
    khuyenMai: "cái quần què",
    danhMuc: {
      idDanhMuc: 2,
      ten: "Tâm lý",
      moTa: "trái tim” là một cuốn sách đặc biệt",
    },
  },
  {
    ten: "Kiếp Nào Ta Cũng Tìm Thấy Nhau: Câu Chuyện Về Những Linh Hồn Tri Kỷ Vĩnh Viễn Không Chia Lìa (Tái Bản)",
    tacGia: "Brian L Weiss",
    nhaXuatBan: "Nhà Xuất Bản Lao Động",
    giaSach: "65.800",
    moTa: "Kiếp nào ta cũng tìm thấy nhau là cuốn sách thứ ba của Brain L. Weiss – một nhà tâm thần học có tiếng. Trước đó ông đã viết hai cuốn sách: cuốn đầu tiên là Ám ảnh từ kiếp trước, cuốn sách mô tả câu chuyện có thật về một bệnh nhân trẻ tuổi cùng với những liệu pháp thôi miên về kiếp trước đã làm thay đổi cả cuộc đời tác giả lẫn cô ấy. Cuốn sách đã bán chạy trên toàn thế giới với hơn 2 triệu bản in và được dịch sang hơn 20 ngôn ngữ. Cuốn sách thứ hai Through Time into Healing (Đi qua thời gian để chữa lành), mô tả những gì tác giả đã học được về tiềm năng chữa bệnh của liệu pháp hồi quy tiền kiếp. Trong cuốn sách đều là những câu chuyện người thật việc thật. Nhưng câu chuyện hấp dẫn nhất lại nằm trong cuốn sách thứ ba.GOETHE",
    hinhAnh:
      "https://lh3.googleusercontent.com/u/0/drive-viewer/AAOQEOTKsEQ3vkK1XDyrli4UVzBjaW4PsouwFm4ulv-2YHsFPklfgGFwCQwM82b5r3kC26RHCb1g2EMpLZk-DXvd6m54lO3zkA=w1920-h892",
    ngayThem: "02/02/2022",
    ngayXuatBan: "02/02/2022",
    ngayCapNhat: "02/02/2022",
    soLuong: "950",
    khuyenMai: "950",
    danhMuc: {
      idDanhMuc: 3,
      ten: "Tâm linh",
      moTa: "trái tim” là một cuốn sách đặc biệt",
    },
  },
  {
    ten: "Nhân Duyên Tiền Kiếp",
    tacGia: "Dick Sutphen",
    nhaXuatBan: "Nhà Xuất Bản Thanh Niên",
    giaSach: "155.000",
    moTa: "“Tuyệt đối không nghi ngờ gì nữa, các cặp đôi đang bên nhau ở kiếp này đã từng ở bên nhau trong nhiều kiếp trước…",
    hinhAnh:
      "https://lh3.googleusercontent.com/u/0/drive-viewer/AAOQEORWp8iprcAq1OtNvwx6WneNTvjHoZw8-3PxtKD_Hy4Cnru3Ru09V1X74hI9b0Ef9zw2MWYSSxdba_5z3Uhd6skKKVyyOA=w1920-h892",
    ngayThem: "11/11/2022",
    ngayXuatBan: "11/11/2022",
    ngayCapNhat: "11/11/2022",
    soLuong: "300",
    khuyenMai: "cái quần què",
    danhMuc: {
      idDanhMuc: 4,
      ten: "Tâm linh",
      moTa: "trái tim” là một cuốn sách đặc biệt",
    },
  },
  {
    ten: "A ! Tết Là Đây !",
    tacGia: "Vũ Linh  Komorebi  Quyên Thái",
    nhaXuatBan: "NXB Kim Đồng",
    giaSach: "68.000",
    moTa: "Một cuốn sách Tết “động đậy” nhất từ trước đến nay dành cho các bé! Tương tác - Tưởng tượng – Thích thú cùng những trang sách đầy bất ngờ, cho bé trải nghiệm những hoạt động và trò chơi nhằm phát triển khả năng sắp xếp, phân loại, tư duy logic và sáng tạo. “Sột soạt…sột…soạt…” Ồ, bé nghe thấy gì không? Cuốn sách đang mời gọi đấy!",
    hinhAnh:
      "https://lh3.googleusercontent.com/u/0/drive-viewer/AAOQEOSfPoB9IQQ1eMvGifHxBTGN3GMQii5mOF2StTuQ3rM7870pO2hRdI5KazKLXt_cZA_PbzISq5Ibl4kgBX20Y3jwoYyq=w1062-h840",
    ngayThem: "17/12/2022",
    ngayXuatBan: "17/12/2022",
    ngayCapNhat: "17/12/2022",
    soLuong: "300",
    khuyenMai: "Cái quần què",
    danhMuc: {
      idDanhMuc: 3,
      ten: "Tâm linh",
      moTa: "trái tim” là một cuốn sách đặc biệt",
    },
  },
  {
    ten: "Bài Học Đầu Đời Cho Bé - Không Được Đụng Vào Đồ Của Tớ",
    tacGia: "Chú Tiểu Dương",
    nhaXuatBan: "NXB Hà Nội",
    giaSach: "38.000",
    moTa: "Giúp Trẻ Biết Chia Sẻ, Nhường Nhịn Và Không Ích Kỷ",
    hinhAnh:
      "https://lh3.googleusercontent.com/u/0/drive-viewer/AAOQEOQBEvktmfdGV0Ur11I6zXjXpo37rvfkfREPZyKcZB60Ntru36jCHTPtNNbZzJh1ylaaLDmp2QvnagByIMZ57bjZsEX18Q=w1920-h892",
    ngayThem: "17/12/2022",
    ngayXuatBan: "17/12/2022",
    ngayCapNhat: "17/12/2022",
    soLuong: "300",
    khuyenMai: "Cái quần què",
    danhMuc: {
      idDanhMuc: 2,
      ten: "Tâm linh",
      moTa: "trái tim” là một cuốn sách đặc biệt",
    },
  },
  {
    ten: "Bánh Mì Kẹp Chuột (Tái Bản 2019)",
    tacGia: "David Walliams",
    nhaXuatBan: "Nhã Nam",
    giaSach: "64.100",
    moTa: "Zoe luôn mơ ước được có một sô diễn xiếc chuột của riêng mình, nhưng chú chuột hamster của con bé đã chết một cách đột ngột, còn chuột cưng mới thì đang gặp nguy hiểm chết người.- The Sun",
    hinhAnh:
      "https://lh3.googleusercontent.com/u/0/drive-viewer/AAOQEOTbx6zMHY2r7yNbOeJvqKynjcsKtOHJ3gBa1-4ki74blWh2FFGLI6-uZGkZlWanoKIW-HstGYAnq1JHo3jSAHXurd1I_w=w1920-h892",
    ngayThem: "04/10/2019",
    ngayXuatBan: "04/10/2019",
    ngayCapNhat: "04/10/2019",
    soLuong: "80",
    khuyenMai: "cái quần què",
    danhMuc: {
      idDanhMuc: 5,
      ten: "Tâm linh",
      moTa: "trái tim” là một cuốn sách đặc biệt",
    },
  },
  {
    ten: "Bịt Mắt Bắt Mèo",
    tacGia: "Lê Thư",
    nhaXuatBan: "NXB Trẻ",
    giaSach: "42.500",
    moTa: "Truyện dài kỳ về Mèo. Các bạn mèo nhà mình sẽ hướng dẫn các bé chơi các trò chơi dân gian theo cách thật sinh động, hài hước, dễ thương.",
    hinhAnh:
      "https://lh3.googleusercontent.com/u/0/drive-viewer/AAOQEOR_hJFeVlxdihYMu_Ketyvb-SId0DaHuEhy1vxiJvawuL24hkAlJmuu9vwTwZB6Wp_T63dTksqLFQmG2h3grat4v5lz0g=w1920-h892",
    ngayThem: "15/03/2023",
    ngayXuatBan: "15/03/2023",
    ngayCapNhat: "15/03/2023",
    soLuong: "5",
    khuyenMai: "cái quần què",
    danhMuc: {
      idDanhMuc: 2,
      ten: "Tâm linh",
      moTa: "trái tim” là một cuốn sách đặc biệt",
    },
  },
  {
    ten: "Câu Hỏi Trẻ Thơ",
    tacGia: "Lê Phương Liên",
    nhaXuatBan: "NXB Kim Đồng",
    giaSach: "74.500",
    moTa: "“Cuốn sách các bạn cầm trên tay đây đã được viết trong 50 năm (1970- 2020). Một tuyển tập bao gồm 25 truyện ngắn và 25 tản văn được chọn từ các truyện ngắn và tản văn đã được giải thưởng trong các cuộc thi văn học, đã được in trên báo, in trong các cuốn sách của riêng tác giả hoặc các tuyển tập chung. Cuốn sách này dành cho mọi lứa tuổi từ các học sinh tiểu học đến các cụ các bác đã nghỉ hưu. Những dòng văn trong cuốn sách là lời tâm tình của một nhà giáo, một nhà văn, một cán bộ biên tập của Nhà xuất bản Kim Đồng và cũng là một người mẹ. Bạn đọc sẽ được theo tác giả đi tới nhiều vùng miền của đất nước Việt Nam và cũng ghé thăm một vài nơi trên thế giới mà tác giả đã có dịp đặt chân đến. Những trang sách mộc mạc này gửi gắm tình cảm yêu thương đến gia đình, quê hương, tới những bạn lớn những người bạn quý đã để lại ấn tượng sâu sắc trong kí ức của tác giả. Hi vọng rằng những trang sách sẽ đem lại cho người đọc những phút giây đầm ấm yêu thương, gửi đến các bạn những suy nghĩ tươi sáng về cuộc sống và con người.” (Nhà văn LÊ PHƯƠNG LIÊN)                                                                                                                                                 “Từ thuở ấu thơ cho đến lúc trưởng thành lẽ sống của tôi là tình yêu thương con người nhất là những người bé bỏng như trẻ em. Tâm tình ấy là do mẹ tôi và bà tôi đã ươm mầm từ khi còn nhỏ. Tôi sớm có một niềm khát khao vươn lên để hiểu biết tinh hoa trí tuệ loài người và mong mỏi được sống trong xã hội thắm tình yêu thương chân thật. Niềm khát khao ấy đã thôi thúc tôi cầm bút viết văn từ tuổi thanh xuân, trải qua những vất vả thăng trầm nỗi niềm ấy vẫn khiến tôi viết tiếp và viết mãi… Phần lớn những dòng chữ trong cuốn sách này tôi đã viết khi mẹ tôi không còn nữa. Mỗi khi viết được những dòng ngay ngắn tôi lại thấy trên cao xanh xa xa, mẹ tôi đang nhìn tôi và mỉm cười trìu mến vô cùng.” (LÊ PHƯƠNG LIÊN)                                                           “Viết cho thiếu nhi rất khó. Viết cho lứa tuổi nhi đồng mẫu giáo còn khó hơn nhiều. Lê Phương Liên đã chọn con đường khó nhất ấy để tạo dựng sự nghiệp cho mình. Với tâm hồn trong trẻo, tinh tế và nhạy cảm, lại thêm lối kể chuyện mộc mạc, giản dị mà không kém phần hấp dẫn, sâu sắc… văn của chị là những món quà đặc biệt đã “thửa” riêng dâng tặng con trẻ và những ai từng là con trẻ.” (Nhà thơ TRẦN ĐĂNG KHOA)",
    hinhAnh:
      "https://lh3.googleusercontent.com/u/0/drive-viewer/AAOQEOSw-OumEa2WSYcHOZH6kpt5Y8qvZYtKJSZimV3R-vZLavAFz3SKmvHLIk7188KpdQtMmhBgQO_pUNqXag7sZtmeiTNsDA=w1920-h892",
    ngayThem: "19/11/2020",
    ngayXuatBan: "19/11/2020",
    ngayCapNhat: "19/11/2020",
    soLuong: "100",
    khuyenMai: "cái quần què",
    danhMuc: {
      idDanhMuc: 4,
      ten: "Tâm linh",
      moTa: "trái tim” là một cuốn sách đặc biệt",
    },
  },
];

export default data;
